#! /usr/bin/tcsh

if ( ! $# ) then
    echo "Usage: $0 [tag]"
    exit(1)
endif

if ( -d $1 ) then

    cd $1
../mkprof.pl -s -t -w ../PPTuneFS00.weights -o Tune00.prof PPXF > & Tune00.prout &
sleep 10
../mkprof.pl -s -t -w ../PPTuneFS70.weights -o Tune70.prof PPXF > & Tune70.prout &
sleep 10
../mkprof.pl -s -t -w ../PPTuneFS28.weights -o Tune28.prof PPXF > & Tune28.prout &
sleep 10
../mkprof.pl -s -t -w ../PPTuneFS09.weights -o Tune09.prof PPXF > & Tune09.prout &
sleep 10
../mkprof.pl -s -t -w ../PPTuneFS02.weights -o Tune02.prof PPXF > & Tune02.prout &
    

else

./mkprof.pl -s -t -w PPTuneFS00.weights -o ${1}00.prof ${1} > & ${1}00.prout &
sleep 10
./mkprof.pl -s -t -w PPTuneFS70.weights -o ${1}70.prof ${1} > & ${1}70.prout &
sleep 10
./mkprof.pl -s -t -w PPTuneFS28.weights -o ${1}28.prof ${1} > & ${1}28.prout &
sleep 10
./mkprof.pl -s -t -w PPTuneFS09.weights -o ${1}09.prof ${1} > & ${1}09.prout &
sleep 10
./mkprof.pl -s -t -w PPTuneFS02.weights -o ${1}02.prof ${1} > & ${1}02.prout &

endif
