#! /usr/bin/tcsh

if ( ! $# ) then
    echo "Usage: $0 [tag] {[basetag]}"
    exit(1)
endif

if ( -d $1 ) then

make ${1}XF
if  ( $status ) then
    echo "Make failed"
    exit(1)
endif

set xsecruns = ""

if ( -e ${1}/PPXF01.run ) then
    set xsecruns = "$xsecruns, ${1}/PPXF01"
endif

if ( -e ${1}/PPXF05.run ) then
    set xsecruns = "$xsecruns, ${1}/PPXF05"
endif

if ( -e ${1}/PPXF18.run ) then
    set xsecruns = "$xsecruns, ${1}/PPXF18"
endif

if ( -e ${1}/PPXF7O.run ) then
    set xsecruns = "$xsecruns, ${1}7O"
endif

if ( -e ${1}/PPXF02.run && -e ${1}/PPXF28.run && -e ${1}/PPXF09.run && -e ${1}/PPXF70.run ) then
    sub.pl -n runtag ./runThePEG, ${1}/PPXF02, ${1}09_1-50, ${1}/PPXF09_51-100, ${1}/PPX28_1-25, ${1}/PPX28_26-50, ${1}/PPX28_51-75, ${1}/PPX28_76-100, ${1}/PPX70_1-20, ${1}/PPX70_21-40, ${1}/PPX70_41-60, ${1}/PPX70_61-80, ${1}/PPX70_81-100 $xsecruns
else
    echo "Could not find all run files"
    exit(1)
endif


else

make ${1}
if  ( $status ) then
    echo "Make failed"
    exit(1)
endif

set xsecruns = ""

if ( -e ${1}01.run ) then
    set xsecruns = "$xsecruns, ${1}01"
endif

if ( -e ${1}05.run ) then
    set xsecruns = "$xsecruns, ${1}05"
endif

if ( -e ${1}18.run ) then
    set xsecruns = "$xsecruns, ${1}18"
endif

if ( -e ${1}7O.run ) then
    set xsecruns = "$xsecruns, ${1}7O"
endif

if ( -e ${1}02.run && -e ${1}28.run && -e ${1}09.run && -e ${1}70.run ) then
    sub runtag ./runThePEG, ${1}02, ${1}09_1-50, ${1}09_51-100, ${1}28_1-25, ${1}28_26-50, ${1}28_51-75, ${1}28_76-100, ${1}70_1-20, ${1}70_21-40, ${1}70_41-60, ${1}70_61-80, ${1}70_81-100 $xsecruns
else
    echo "Could not find all run files"
    exit(1)
endif

endif
