#!/usr/bin/perl -w

use strict;
my @files;

foreach my $arg ( @ARGV ) {

    if ( $arg =~ /^(\S+)\// ) {
	push @files, "$arg:$1";
    } else {
	push @files, "$arg";
    }
}

system("export RIVET_ANALYSIS_PATH=./refs; rivet-mkhtml @files\n");

