#! /bin/csh -f

if ( $#argv > 0 ) then
    set rzfile = ${1}.rz
    set rzfile2 = ${1}.rz
    set psfile = ${1}.ps
else
    echo "Usage: $0 file {reffile}"
    exit 1
endif

if ( $#argv > 1 ) then
    set rzfile2 = ${2}.rz
endif

/usr/local/cern/2002b/bin/pawX11 > last.out <<EOF
0
fort/file 99 $psfile
h/file 50 $rzfile
h/file 51 $rzfile2
h/cre/tit $1
meta 99 -111

set xsiz 21
set ysiz 29.0
set xwin 1.5
set ywin 1.5
set pass 3
set ymgl 1.5
set ymgu 1.5
set xmgl 1.5
set xmgr 0.5
set ygti 0.5
set gsiz 0.5
set yhti 1.0
opt nbox

zone 3 5

opt linx
opt liny
set dmod 1
h/plot //lun50/95108/11 HIST
set dmod 2
h/plot //lun51/95108/11 S,HIST
set dmod 1
h/plot //lun50/95108/-11 S

set dmod 1
h/plot //lun50/95108/15 HIST
set dmod 2
h/plot //lun51/95108/15 S,HIST
set dmod 1
h/plot //lun50/95108/-15 S

set dmod 1
h/plot //lun50/95108/19 HIST
set dmod 2
h/plot //lun51/95108/19 S,HIST
set dmod 1
h/plot //lun50/95108/-19 S

opt linx
opt logy
set dmod 1
h/plot //lun50/96215/-13000
set dmod 1
h/plot //lun50/96215/13000 S,HIST
set dmod 2
h/plot //lun51/96215/13000 S,HIST
set dmod 1

h/plot //lun50/96215/-13003
set dmod 1
h/plot //lun50/96215/13003 S,HIST
set dmod 2
h/plot //lun51/96215/13003 S,HIST

opt linx
opt liny
set dmod 1
h/plot //lun50/96215/12000 HIST
set dmod 2
h/plot //lun51/96215/12000 S,HIST
set dmod 1
h/plot //lun50/96215/-12000 S

set dmod 1
h/plot //lun50/96215/12003 HIST
set dmod 2
h/plot //lun51/96215/12003 S,HIST
set dmod 1
h/plot //lun50/96215/-12003 S

opt logx
set dmod 1
h/plot //lun50/98076/-120
set dmod 1
h/plot //lun50/98076/120 S,HIST
set dmod 2
h/plot //lun51/98076/120 S,HIST

opt logx
set dmod 1
h/plot //lun50/98051/-1
set dmod 1
h/plot //lun50/98051/1 S,HIST
set dmod 2
h/plot //lun51/98051/1 S,HIST

opt logx
opt logy
set dmod 1
h/plot //lun50/98051/-720
set dmod 1
h/plot //lun50/98051/720 S,HIST
set dmod 2
h/plot //lun51/98051/720 S,HIST

opt linx
opt liny
set dmod 1
h/plot //lun50/98143/-1301
set dmod 1
h/plot //lun50/98143/301 S,HIST
set dmod 2
h/plot //lun51/98143/301 S,HIST

opt linx
opt liny
set dmod 1
h/plot //lun50/98143/-1302
set dmod 1
h/plot //lun50/98143/302 S,HIST
set dmod 2
h/plot //lun51/98143/302 S,HIST

opt linx
opt liny
set dmod 1
h/plot //lun50/98143/-1303
set dmod 1
h/plot //lun50/98143/303 S,HIST
set dmod 2
h/plot //lun51/98143/303 S,HIST

opt linx
opt liny
set dmod 1
h/plot //lun50/98143/-1304
set dmod 1
h/plot //lun50/98143/304 S,HIST
set dmod 2
h/plot //lun51/98143/304 S,HIST

set dmod 1
h/plot //lun50/98143/305
set dmod 1
h/plot //lun50/98143/305 S,HIST
set dmod 2
h/plot //lun51/98143/305 S,HIST

set dmod 1
h/plot //lun50/98143/309 HIST
set dmod 2
h/plot //lun51/98143/309 S,HIST


meta 0
close 99

quit
EOF
if ( $0 == "pmkps" ) then
  lpr ../$psfile:al
endif

if ( $0 == "vmkps" ) then
  gv ../$psfile:al &
endif

if ( $0 == "gmkps" || $0 == "MCEG/Projects/LDCtune/gmkps" || $0 == "/home/nimis/leif/MCEG/Projects/LDCtune/gmkps" ) then
  gzip ../$psfile:al
endif
